apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: s5h4te5ao-go 
  janus-idp.io/tekton: s5h4te5ao-go
  backstage.io/kubernetes-id: s5h4te5ao-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s5h4te5ao-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml