apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s5h4te5ao-go-gitops
  description: This is GitOps manifest for s5h4te5ao-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=s5h4te5ao-go
    backstage.io/kubernetes-id: s5h4te5ao-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: s5h4te5ao-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:s5h4te5ao-go
