apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s5h4te5ao-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s5h4te5ao-go 
  name: s5h4te5ao-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: s5h4te5ao-go 
